#!/bin/bash
#
# Scripts in this directory are run during the build process.
# each script will be uploaded to /tmp on your build droplet,
# given execute permissions and run.  The cleanup process will
# remove the scripts from your build system after they have run
# if you use the build_image task.
#

wget https://dl.influxdata.com/telegraf/releases/telegraf_1.9.4-1_amd64.deb
sudo dpkg -i telegraf_1.9.4-1_amd64.deb
sudo systemctl stop telegraf

wget https://dl.influxdata.com/influxdb/releases/influxdb_1.7.2_amd64.deb
sudo dpkg -i influxdb_1.7.2_amd64.deb
sudo systemctl stop influxdb

wget https://dl.influxdata.com/chronograf/releases/chronograf_1.7.7_amd64.deb
sudo dpkg -i chronograf_1.7.7_amd64.deb
sudo systemctl stop chronograf

wget https://dl.influxdata.com/kapacitor/releases/kapacitor_1.5.2_amd64.deb
sudo dpkg -i kapacitor_1.5.2_amd64.deb
sudo systemctl stop kapacitor

rm -r telegraf* influxdb* chronograf* kapacitor*

echo "INFLUXDB_HTTP_AUTH_ENABLED=true" >> /etc/default/influxdb

apt-get -y update
apt-get -y upgrade

mv /tmp/telegraf.conf /etc/telegraf/telegraf.conf
